### PR TITLE
Provide publisher ktoso rebased

### PR DESCRIPTION
**Pull request by viktorklang**
This is a rebase of #186 on current master.

### CODE REVIEW

**Comment by viktorklang** [comment]
@ktoso I rebased your branch on top of current master, I don't get any test failures locally so I cannot reproduce. Can you have a look?

**Comment by ktoso** [comment]
I'll be at my machine soon, will have a look right away. :-)

-- 
Konrad
(sent from mobile)

**Comment by ktoso** [comment]
Works for me locally... Opened a new PR with my rebased branch as well as including "gradle, gimme the stacktrace" option, so we actually can find something from those failures (unlike now).

**Comment by viktorklang** [comment]
Just testing to see what Travis says

**Comment by ktoso** [comment]
Figured out the problems and addressed in https://github.com/reactive-streams/reactive-streams/pull/193 which superseeds this PR. I think we should close this one here.

**Comment by viktorklang** [comment]
@ktoso closing.

**Pull request closed without merging**
