### PR TITLE
make build.gradle support idea and eclipse

### PR DESCRIPTION
**Pull request by darionyaphet**
add some lines on build.gradle to support idea and eclipse

### CODE REVIEW

**Comment by viktorklang** [comment]
Hi @darionyaphet,

Welcome to Reactive Streams!

We discussed this a while back and the consensus was to put those plugins in your user/global gradle config. Does that work for you?

Cheers,
√

**Comment by darionyaphet** [comment]
hi cherrs 
Actually I don't know how to use user/global gradle config . 
I reading Kafka's gradle config file , Kafka put this config into build.gradle .
And what is difference put it into diff config-file ? thank you for you help :)

**Comment by viktorklang** [comment]
Does this help?
https://stackoverflow.com/questions/11567786/global-plugins-in-gradle

**Comment by darionyaphet** [comment]
yes ! 
This support is very useful and many project will use it . 
Put it into global config maybe better :+1:

**Comment by viktorklang** [comment]
Fantastic!

I'll close this PR then :)

Cheers,
√

**Pull request closed without merging**
